config/routes.rb
Omglambda::Application.routes.draw do
  resources :import_tables
  post "import_tables/:id" => 'import_tables#merge'

  get "csv/import"
  post "csv/import" => "csv#upload"

end

app/models/household.rb
class Household < ActiveRecord::Base
  attr_accessible :address, :delivery_point, :epsilon_key, :plus_4, :zip
end

app/models/import_cell.rb
class ImportCell < ActiveRecord::Base
  attr_accessible :column_index, :contents, :import_table_id, :row_index
  belongs_to :import_table
end

app/models/import_table.rb
class ImportTable < ActiveRecord::Base
  attr_accessible :original_path
  has_many :import_cells, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/csv_controller.rb
class CsvController < ApplicationController
  require 'csv'
  def import
  end

  def upload
    table = ImportTable.new :original_path => params[:upload][:csv].original_filename
    row_index = 0
    CSV.parse(params[:upload][:csv].read) do |cells|
      column_index = 0
      cells.each do |cell|
        table.import_cells.build :column_index => column_index, :row_index => row_index, :contents => cell
        column_index += 1
      end
      row_index += 1
    end
    table.save
    import_table_path(table)
    render :text => params.to_json 
  end
end

app/controllers/import_tables_controller.rb
class ImportTablesController < ApplicationController
  # GET /import_tables
  # GET /import_tables.json
  def index
    @import_tables = ImportTable.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @import_tables }
    end
  end

  # GET /import_tables/1
  # GET /import_tables/1.json
  def show
    @import_table = ImportTable.find(params[:id])
    @import_cells = @import_table.import_cells
    @row_index_max = @import_cells.map { |cell| cell.row_index }.max
    @column_index_max = @import_cells.map { |cell| cell.column_index }.max
    @tables = ActiveRecord::Base.connection.tables.select { |t| t != 'schema_migrations' }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @import_table }
    end
  end

  # GET /import_tables/new
  # GET /import_tables/new.json
  def new
    @import_table = ImportTable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @import_table }
    end
  end

  # GET /import_tables/1/edit
  def edit
    @import_table = ImportTable.find(params[:id])
  end

  # POST /import_tables
  # POST /import_tables.json
  def create
    @import_table = ImportTable.new(params[:import_table])

    respond_to do |format|
      if @import_table.save
        format.html { redirect_to @import_table, notice: 'Import table was successfully created.' }
        format.json { render json: @import_table, status: :created, location: @import_table }
      else
        format.html { render action: "new" }
        format.json { render json: @import_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /import_tables/1
  # PUT /import_tables/1.json
  def update
    @import_table = ImportTable.find(params[:id])

    respond_to do |format|
      if @import_table.update_attributes(params[:import_table])
        format.html { redirect_to @import_table, notice: 'Import table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @import_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /import_tables/1
  # DELETE /import_tables/1.json
  def destroy
    @import_table = ImportTable.find(params[:id])
    @import_table.destroy

    respond_to do |format|
      format.html { redirect_to import_tables_url }
      format.json { head :no_content }
    end
  end

  def merge
    import_table = ImportTable.find(params[:id])
    import_cells = import_table.import_cells
    row_index_max = import_cells.map { |cell| cell.row_index }.max
    column_index_max = import_cells.map { |cell| cell.column_index }.max

    # Pull the merge parameters from the POST request. The form sets up the
    # column mappings and merge table choice. Then use a little bit of
    # ActiveRecord introspection to derive the table's class name followed by
    # the class object. We will use this latter object to instantiate the
    # merged records.
    merge = params[:merge]
    merge_table = merge[:table]
    klass = merge_table.classify.constantize


    # Determine which columns have been mapped. Ignore the rest. Intersect the
    # requested column names with actual column names. Perhaps we should abort
    # and display some error message if the intersection proves empty because
    # the user did not select any columns.
    inverted_merge = merge.invert
    column_names = inverted_merge.keys & klass.column_names

    # Finally, create new instances, one per row. Iterate the rows, then for
    # each row, iterate the mapped columns. Select the matching cell and
    # update the record's corresponding column. Redirect to the merged table
    # when done.
    0.upto(row_index_max) do |row_index|
      row = import_cells.select { |cell| cell.row_index == row_index }
      instance = klass.new
      column_names.each do |column_name|
        column_index = inverted_merge[column_name].to_i
        contents = row.select { |cell| cell.column_index == column_index }[0].contents
        instance[column_name] = contents
      end
      instance.save
    end
    redirect_to import_tables_url, notice: "Import was successful"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csv_helper.rb
module CsvHelper
end

app/helpers/import_tables_helper.rb
module ImportTablesHelper
end

app/views/csv/import.html.erb
<h1>Csv#import hai</h1>
<p>Find me in app/views/csv/import.html.erb</p>
<%= form_for :upload, :html => { :multipart => true } do |f| -%>
  <%= f.file_field :csv %>
  <%= f.submit "Upload", :disable_with => 'Uploading...' %>
<% end -%>

app/views/import_tables/_form.html.erb
<%= form_for(@import_table) do |f| %>
  <% if @import_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@import_table.errors.count, "error") %> prohibited this import_table from being saved:</h2>

      <ul>
      <% @import_table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :original_path %><br />
    <%= f.text_field :original_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/import_tables/edit.html.erb
<h1>Editing import_table</h1>

<%= render 'form' %>

<%= link_to 'Show', @import_table %> |
<%= link_to 'Back', import_tables_path %>

app/views/import_tables/index.html.erb
<h1>Listing import_tables</h1>

<table>
  <tr>
    <th>Original path</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @import_tables.each do |import_table| %>
  <tr>
    <td><%= import_table.original_path %></td>
    <td><%= link_to 'Show', import_table %></td>
    <td><%= link_to 'Edit', edit_import_table_path(import_table) %></td>
    <td><%= link_to 'Destroy', import_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Import table', new_import_table_path %>

app/views/import_tables/new.html.erb
<h1>New import_table</h1>

<%= render 'form' %>

<%= link_to 'Back', import_tables_path %>

app/views/import_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<b>Original path:</b>
<%= @import_table.original_path %>
</p>

<%= form_for :merge do |f| -%>
  <table border="1" cellspacing="1" cellpadding="1">
    <tr>
      <% 0.upto(@column_index_max) do |column_index| %>
        <th>
          <%= f.select(column_index, []) %>
        </th>
      <% end %>
    </tr>
    <% 0.upto(@row_index_max) do |row_index| %>
      <% row = @import_cells.select { |cell| cell.row_index == row_index } %>
      <tr>
        <% 0.upto(@column_index_max) do |column_index| %>
          <td>
            <%= row.select { |cell| cell.column_index == column_index }[0].contents %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <label><%= 'Select a table for merging:' %></label>
  <%= f.select(:table, @tables.collect { |t| [t, t] }, { :include_blank => true }, { :onchange => "mergeTableSelected();" }) %>
  <%= f.submit "Merge", :disable_with => 'Merging...' %>
<% end -%>

<%= javascript_tag do -%>
  var columns = new Array();
  <% for table in @tables -%>
    <% for column in table.classify.constantize.columns %>
      columns.push(new Array('<%= table %>', '<%= column.name %>'));
    <% end -%>
  <% end -%>
  function mergeTableSelected() {
  var o = $('select#merge_table option:selected');
  $('th select option').remove();
  $('th select').each(function(i, select) {
  select.options.add(new Option());
  $.each(columns, function(j, column) {
  if (o.text() == column[0]) {
  select.options.add(new Option(column[1]));
  }
  });
  });
  }
<% end -%>

<%= link_to 'Edit', edit_import_table_path(@import_table) %> |
<%= link_to 'Back', import_tables_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Omglambda</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <button class="close" data-dismiss="alert">x</button>
        <%= msg  %>
      </div>
    <% end %>
    <%= yield %>

  </body>
</html>